name: Add a point

on:
  schedule:
    - cron: "40 13 * * *"
  workflow_dispatch:

env:
  POINT_TOKEN: ${{ secrets.POINT_TOKEN }}
  GIT_USER: ${{ secrets.GIT_USER }}
  GIT_EMAIL: ${{ secrets.GIT_EMAIL }}

permissions:
  contents: write

jobs:
  add-point:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.POINT_TOKEN }}

      - name: Push a point to the repository
        run: |
          git config --global user.name "${GIT_USER}"
          git config --global user.email "${GIT_EMAIL}"

          echo "Adding a point to the repository"
          echo "Point added on $(date)" >> POINT.txt

          git add POINT.txt
          git commit -m "Add a point on $(date)" || echo "Nothing to commit"
          git push origin HEAD
